services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dev-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306
    ports:
      - "8080:80"

