services:
  golang:
    image: golang:latest
    container_name: dev-golang
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "8082:8080"
    command: bash
